### ISSUE TITLE
Swift 4: 'amx_autoScaleFont' cannot be used on type

### ISSUE THREAD

**Issue by robhunter** [alexmx/AMXFontAutoScale#7]
When upgrading to Swift 4, I see the following errors:

Instance member 'amx_autoScaleFont' cannot be used on type 'UILabel'; did you mean to use a value of this type instead?

Instance member 'amx_autoScaleFont' cannot be used on type 'UITextView'; did you mean to use a value of this type instead?

My only AMX code is in my didFinishLaunchingWithOptions:

UILabel.amx_autoScaleFont(forReferenceScreenSize: .size5p5Inch)
UITextView.amx_autoScaleFont(forReferenceScreenSize: .size5p5Inch)

**Comment by robhunter** [comment]
This is a problem in Swift 3.2 as well.

**Comment by robhunter** [comment]
It looks like under Swift 3.2+ these declarations are broken/not importing correctly:

https://github.com/alexmx/AMXFontAutoScale/blob/master/AMXFontAutoScale/UILabel%2BAMXFontScale.m#L22
https://github.com/alexmx/AMXFontAutoScale/blob/master/AMXFontAutoScale/UITextView%2BAMXFontScale.m#L22

A workaround is to change the following:

UILabel.amx_autoScaleFont(forReferenceScreenSize: .size5p5Inch)
UITextView.amx_autoScaleFont(forReferenceScreenSize: .size5p5Inch)

to this:

UILabel.amx_autoScaleEnabled = true
UILabel.amx_referenceScreenSize = .size5p5Inch
UITextView.amx_autoScaleEnabled = true
UITextView.amx_referenceScreenSize = .size5p5Inch

**Comment by alexmx** [comment]
@robhunter Thanks for reporting this. 

It is working fine in Xcode 8.3 but seems broken in Xcode 9.
Will take a look later today, might be a bug in the latest Swift compiler.

**Comment by alexmx** [comment]
Fixed the issue. Please update to [release 1.1.2](https://github.com/alexmx/AMXFontAutoScale/releases/tag/v1.1.2)

The fix is quite weird: https://github.com/alexmx/AMXFontAutoScale/commit/67226723a2264cd26db8fdff6dd61ff5f868671d#diff-3666655fb9849b281fc5f9579ad5c9efR38

It seems that the instance method collides with the static (class) method if they have the same name.
As I said, seems to be the bug in the latest Swift compiler. Will report it in the Swift project JIRA.

Regards,
Alex
